/**
 * Marginalia & Marigold design system — content synchronizer.
 * The canonical source remains in ../../digital notes; this script emits website-ready data.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repositoryRoot = path.resolve(__dirname, '../..');
const subjectsRoot = path.join(repositoryRoot, 'digital notes', 'subjects');
const outputPath = path.join(repositoryRoot, 'website', 'src', 'library.generated.ts');
const owner = 'prayasdev';
const repository = 'lecture-notes';
const branch = 'main';

const rawUrl = (relativePath) =>
  `https://raw.githubusercontent.com/${owner}/${repository}/${branch}/${relativePath
    .split(path.sep)
    .map(encodeURIComponent)
    .join('/')}`;

const readJson = (file) => JSON.parse(fs.readFileSync(file, 'utf8'));
const subjectDirectories = fs
  .readdirSync(subjectsRoot, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort();

const subjects = subjectDirectories.map((subjectSlug) => {
  const subjectDirectory = path.join(subjectsRoot, subjectSlug);
  const manifest = readJson(path.join(subjectDirectory, 'manifest.json'));
  const modules = manifest.modules.map((module) => {
    const markdownPath = path.join(subjectDirectory, 'modules', module.id, module.file);
    const repoRelativeModulePath = path.relative(repositoryRoot, markdownPath);
    const content = fs.readFileSync(markdownPath, 'utf8').replaceAll(
      '](assets/',
      `](${rawUrl(path.relative(repositoryRoot, path.join(subjectDirectory, 'modules', module.id, 'assets')))} /`
    );

    const normalizedContent = content.replaceAll(' /', '/');
    return {
      ...module,
      sourcePath: repoRelativeModulePath.split(path.sep).join('/'),
      rawUrl: rawUrl(repoRelativeModulePath),
      content: normalizedContent,
    };
  });

  const legacy = (manifest.legacy || []).map((resource) => ({
    ...resource,
    rawUrl: rawUrl(path.join('digital notes', 'subjects', subjectSlug, resource.path)),
  }));

  return { ...manifest, modules, legacy };
});

const source = `/**\n * Generated by website/scripts/sync-notes.mjs.\n * Do not edit manually; update digital notes manifests or Markdown sources, then run the sync script.\n */\nexport const library = ${JSON.stringify(
  { owner, repository, branch, subjects },
  null,
  2,
)} as const;\n`;

fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, source, 'utf8');
console.log(`Synced ${subjects.length} subject(s) to ${path.relative(repositoryRoot, outputPath)}`);
